CREATE DATABASE CITY_HOSPITAL;
USE CITY_HOSPITAL;
CREATE table PATIENTS(
PATIENT_ID int primary key,
PATIENT_NAME varchar (50),
AGE int,
GENDER enum ('M','F'),
ADMISSION_DATE date);

ALTER TABLE PATIENTS
ADD DOCTOR_ASSIGNED varchar(50);

ALTER TABLE PATIENTS
MODIFY PATIENT_NAME VARCHAR(100);

RENAME TABLE PATIENTS TO PATIENT_INFO;

TRUNCATE TABLE PATIENT_INFO;

DROP TABLE PATIENT_INFO;





