CREATE DATABASE ONLINE_BOOKSTORE;
USE ONLINE_BOOKSTORE;
CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
BOOK_NAME varchar (100),
AUTHOR_NAME VARCHAR (50),
ISSUE_DATE DATE);

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY,
BOOK_ID INT,
ORDER_DATE DATE,
OEDER_NUMBER INT,
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID));

ALTER TABLE BOOKS
ADD COLUMN ISBN INT unique;

DELETE FROM ORDERS WHERE
ORDER_DATE <'2018-01-01';

TRUNCATE TABLE ORDERS;








